### ISSUE TITLE
FineTuning and Resume training

### ISSUE THREAD

**Issue by deepseek** [masyagin1998/robin#4]
@masyagin1998 Thank you for your amazing and well-written code, you are appreciated,

Have you considered the option of finetuning an existing model, or perhaps the ability to resume the training using an existing model?

**Comment by masyagin1998** [comment]
Hello, my friend!
Thank You for high rating my code!
While I was writing Robin, I thought about adding some cargs for tunning model, but finally I decided not to add them, because model is stored in separate filer and it is simpler to hardcode new model.
About resuming training - I can implement this feature in my free time (I hope that I will have some free time on summer holidays XD ), or You can write it by yourself and create pull-request :)

**Comment by mrocr** [comment]
or you I can make a donation to help you speed thins up :sunglasses: 
add `.github/FUNDING.yml` file to `master` so I can donate.

**Comment by deepseek** [comment]
or you I can make a donation to help you speed things up :sunglasses: 
add `.github/FUNDING.yml` file to `master` so I can donate.

**Comment by masyagin1998** [comment]
Well, I can add `FUNDING.yml` in few days :D

**Comment by deepseek** [comment]
:)

**Comment by douhaopeng** [comment]
I cannot run your project

**Comment by masyagin1998** [comment]
It is better to create separate issue or tell me, what's problems do You have
